name: GT3Photography
favicon: null
layout_spectrum: 0.24773
typography_spectrum: 0.19145374302752316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33323a'
    - '#4c4b51'
    - '#827f7a'
    - '#bcac9d'
    - '#e1ddd9'
  brandStrength: 0.5
  lightness: 0.2163739101961255
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
